### ISSUE TITLE
bash 혼자 집에 도달한 문제

### ISSUE THREAD

**Issue by tnRaro** [riemannulus/i_want_go_home#13]
https://github.com/riemannulus/i_want_go_home/blob/775ae9f1f49212e3b4229188e1312a8d247a4fec/bash/i_want_go_home.sh#L3-L4

bash 혼자 집에 도착해놓고, 집에 가고 싶다고 말하고 있습니다.
bash의 기만을 멈춰주세요.

**Comment by wonjinYi** [comment]
동의합니다. 이는 프로젝트에 대한 기만입니다.

**Comment by riemannulus** [comment]
인정합니다. `cd $HOME` 을 제거해야 합니다.
