### ISSUE TITLE
오버엔지니어링(?)을 해도 괜찮나요?

### ISSUE THREAD

**Issue by Danue1** [riemannulus/i_want_go_home#43]
다른 기여를 참고하면서 PR 하고 보니, 단순히 main 함수 실행하는 즉시 print만 하는 것은 단조로운 것 같다는 생각이 들었습니다.

**Comment by riemannulus** [comment]
기교를 부려도 괜찮지만, 접근성을 신경쓰면서 작성해주시면 감사하겠습니다!

**Comment by Danue1** [comment]
아하, 알겠습니다.
