### ISSUE TITLE
Ne estas Esperanta dokumento.

### ISSUE THREAD

**Issue by nyeong** [riemannulus/i_want_go_home#58]
Ne estas Esperanta dokumento. Homoj tra la mondo ankaŭ volas hejmeniri.
La nomo de dokumento estu `esperanto/esperanto.txt` kaj la enhavo estu `Mi volas iri al hejmen`.

[에스페란토](https://en.wikipedia.org/wiki/Esperanto)로 된 문서가 없습니다. 세계인들도 집에 가고 싶어합니다.
문서 이름은 `esperanto/esperanto.txt`가, 내용은 `Mi volas iri hejmen`이 좋겠습니다.

**Comment by Danue1** [comment]
직접 PR해도 괜찮을 것 같아요!

**Comment by nyeong** [comment]
넵 제가 직접 하겠습니다 😊
